language: scala
matrix:
  include:
  - scala: 2.10.6
    jdk: oraclejdk7
  - scala: 2.11.8
    jdk: oraclejdk8
  - scala: 2.12.0
    jdk: oraclejdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION clean test
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
git:
  depth: 1
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
